#include <catch.hpp>
#include <string>
#include <vector>

#include "SP/InvalidSyntaxException.h"
#include "SP/Parser.h"
#include "SP/Utilities/CallLoopChecker.h"

/*
 * Naming Convention:
 * functionName - Positive/Negative Case - (Opt: Others)
 *
 * E.g.
 * tokenizeRelFactor - Negative Case - Very Nested Blocks
 */

TEST_CASE("checkCallLoop - Positive Case")
{
    string rawSourceCode = "procedure main {\n"
                           "\tprint = x;\n"
                           "\tread x;\n"
                           "\tleft = x;\n"
                           "\tcall somethingHmm;\n"
                           "\tright = left + 2;\n"
                           "\tread temp;\n"
                           "\tradius = x + left;\n"
                           "\ttemp = temp + 2;\n"
                           "\tradius1 = x + left;\n"
                           "\tcall anotherOne;\n"
                           "}\n"
                           "\n"
                           "procedure somethingHmm {\n"
                           "\twhile (iter <=  5) {\n"
                           "\t\tx = right + 3 + 2 + left;\n"
                           "\t\ttemp = temp + 7;\n"
                           "\t\tcall anotherOne;\n"
                           "\t}\n"
                           "\tx = 5;\n"
                           "\tif (iter != 1) then {\n"
                           "\t\titer = iter + 1; \n"
                           "\t\tlength = radius * 10;\n"
                           "\t\tbreadth = radius + 10;\n"
                           "\t} else {\n"
                           "\t\twhile ((left + 1 > 2) || (radius + 1 > 2)) {\n"
                           "\t\t\tcall nestedBlocks;\n"
                           "\t\t\tlength = left + right;\n"
                           "\t\t}\n"
                           "\t}\n"
                           "}\n"
                           "\n"
                           "procedure nestedBlocks {\n"
                           "\tif (iter != 1) then {\n"
                           "\t\titer = iter + 1; \n"
                           "\t\tlength = radius * 10;\n"
                           "\t\tbreadth = radius + 10;\n"
                           "\t} else {\n"
                           "\t\twhile ((left + 1 > 2) || (radius + 1 > 2)) {\n"
                           "\t\t\tbreadth = radius - 100;\n"
                           "\t\t\tlength = left + right;\n"
                           "\t\t\tcall anotherOne;\n"
                           "\t\t\tif (1 > 2) then {\n"
                           "\t\t\t\tprocedure  = 5;\n"
                           "\t\t\t} else {\n"
                           "\t\t\t\tlength = no;\n"
                           "\t\t\t\twhile ((x > 2) || !(y <= 5)) {\n"
                           "\t\t\t\t\tcall anotherOne;\n"
                           "\t\t\t\t}\n"
                           "\t\t\t}\n"
                           "\t\t}\n"
                           "\t}\n"
                           "}\n"
                           "\n"
                           "procedure anotherOne {\n"
                           "\tprint x;\n"
                           "}";

    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");
    REQUIRE(!CallLoopChecker::checkCallLoop(AST));
}

TEST_CASE("checkCallLoop - Positive Case - HARD 2")
{
    string rawSourceCode = "procedure procedure1 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { then = then + if; while = procedure + 32432 + if + then;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call procedure4; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure3; } else { print x; }\n"
                           "        while (x < y) { call procedure2; }} else { while (else < if) { call procedure2; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure2 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { then = then + if; while = procedure + 32432 + if + then;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call procedure4; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { read x; } else { print x; }\n"
                           "        while (x < y) { call procedure3; }} else { while (else < if) { call procedure3; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure3 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { then = then + if; while = procedure + 32432 + if + then;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { print call; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { read x; } else { print x; }\n"
                           "        while (x < y) { call procedure4; }} else { while (else < if) { call procedure4; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure4 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { then = then + if; while = procedure + 32432 + if + then;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { print call; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { read x; } else { print x; }\n"
                           "        while (x < y) { call procedure5; }} else { while (else < if) { call procedure5; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure5 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure12; call procedure15;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure6; }} else { while (else < if) { call procedure6; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure6 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure16; call procedure12;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure7; }} else { while (else < if) { call procedure7; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure7 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure13;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure25; } else { print x; }\n"
                           "        while (x < y) { call procedure8; }} else { while (else < if) { call procedure8; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure8 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure45; call procedure37;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure9; }} else { while (else < if) { call procedure9; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure9 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure13; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure12; } else { print x; }\n"
                           "        while (x < y) { call procedure10; }} else { while (else < if) { call procedure10; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure10 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure48; } else { print x; }\n"
                           "        while (x < y) { call procedure11; }} else { while (else < if) { call procedure11; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure11 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure25; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure37; } else { print x; }\n"
                           "        while (x < y) { call procedure12; }} else { while (else < if) { call procedure12; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure12 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure19; call procedure15;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure13; }} else { while (else < if) { call procedure13; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure13 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure20;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure14; }} else { while (else < if) { call procedure14; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure14 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure44; call procedure47;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure37; } else { print x; }\n"
                           "        while (x < y) { call procedure15; }} else { while (else < if) { call procedure15; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure15 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure45;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure25; } else { print x; }\n"
                           "        while (x < y) { call procedure16; }} else { while (else < if) { call procedure16; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure16 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure20; call procedure47;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure48; } else { print x; }\n"
                           "        while (x < y) { call procedure17; }} else { while (else < if) { call procedure17; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure17 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure41; } else { print x; }\n"
                           "        while (x < y) { call procedure18; }} else { while (else < if) { call procedure18; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure18 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure21; call procedure20;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure19; }} else { while (else < if) { call procedure19; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure19 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure21; call procedure24;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure37; } else { print x; }\n"
                           "        while (x < y) { call procedure20; }} else { while (else < if) { call procedure20; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure20 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure45; call procedure44;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure21; }} else { while (else < if) { call procedure21; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure21 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure33;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure25; } else { print x; }\n"
                           "        while (x < y) { call procedure22; }} else { while (else < if) { call procedure22; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure22 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure45;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure23; }} else { while (else < if) { call procedure23; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure23 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure35;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure48; } else { print x; }\n"
                           "        while (x < y) { call procedure24; }} else { while (else < if) { call procedure24; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure24 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure44; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure37; } else { print x; }\n"
                           "        while (x < y) { call procedure25; }} else { while (else < if) { call procedure25; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure25 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure35; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure26; }} else { while (else < if) { call procedure26; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure26 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure33; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure41; } else { print x; }\n"
                           "        while (x < y) { call procedure27; }} else { while (else < if) { call procedure27; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure27 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure44;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure35; } else { print x; }\n"
                           "        while (x < y) { call procedure28; }} else { while (else < if) { call procedure28; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure28 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure33;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure29; }} else { while (else < if) { call procedure29; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure29 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure48; } else { print x; }\n"
                           "        while (x < y) { call procedure30; }} else { while (else < if) { call procedure30; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure30 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure33; } else { print x; }\n"
                           "        while (x < y) { call procedure31; }} else { while (else < if) { call procedure31; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure31 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure35; } else { print x; }\n"
                           "        while (x < y) { call procedure32; }} else { while (else < if) { call procedure32; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure32 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure41; } else { print x; }\n"
                           "        while (x < y) { call procedure33; }} else { while (else < if) { call procedure33; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure33 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure35; call procedure48;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure46; } else { print x; }\n"
                           "        while (x < y) { call procedure34; }} else { while (else < if) { call procedure34; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure34 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure35; }} else { while (else < if) { call procedure35; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure35 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure41; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure36; }} else { while (else < if) { call procedure36; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure36 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure42; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure43; } else { print x; }\n"
                           "        while (x < y) { call procedure37; }} else { while (else < if) { call procedure37; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure37 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure38; }} else { while (else < if) { call procedure38; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure38 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure43;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure42; } else { print x; }\n"
                           "        while (x < y) { call procedure39; }} else { while (else < if) { call procedure39; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure39 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure46; call procedure41;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure40; }} else { while (else < if) { call procedure40; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure40 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure42;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure41; }} else { while (else < if) { call procedure41; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure41 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure43;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure42; }} else { while (else < if) { call procedure42; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure42 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure46; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure43; }} else { while (else < if) { call procedure43; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure43 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure47; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure44; }} else { while (else < if) { call procedure44; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure44 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call procedure46;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure47; } else { print x; }\n"
                           "        while (x < y) { call procedure45; }} else { while (else < if) { call procedure45; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure45 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure46; }} else { while (else < if) { call procedure46; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure46 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure47; }} else { while (else < if) { call procedure47; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure47 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call procedure50; } else { print x; }\n"
                           "        while (x < y) { call procedure48; }} else { while (else < if) { call procedure48; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure48 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call procedure50; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure49; }} else { while (else < if) { call procedure49; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure49 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call procedure50; }} else { while (else < if) { call procedure50; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure procedure50 {\n"
                           "  while (while < while) { if (if != if * (2 + 1)) then { call end; call end;\n"
                           "      else = while; } else { else = if + then + procedure; while (5 > 0) { if (then > (else - procedure) * (then / 9342) + while) then { print print;\n"
                           "        } else { while (procedure >= then) { call end; }}} while (procedure <= else + while) {\n"
                           "        if ((x + 1) * (2 / 3) == 1 + 2 / 6 % 3 + 5 + 6 * 2 % 2) then { if (read == print) then { call end; } else { print x; }\n"
                           "        while (x < y) { call end; }} else { while (else < if) { call end; }}}}}\n"
                           "}\n"
                           "\n"
                           "procedure end {\n"
                           "  print x;\n"
                           "}";

    Statement::resetLineNumCount();
    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");

    REQUIRE(!CallLoopChecker::checkCallLoop(AST));
}

TEST_CASE("checkCallLoop - Negative Case - Recursive call")
{
    string rawSourceCode = "procedure main {\n"
                           "\tprint = x;\n"
                           "\tread x;\n"
                           "\tleft = x;\n"
                           "\tright = left + 2;\n"
                           "\tread temp;\n"
                           "\tradius = x + left;\n"
                           "\ttemp = temp + 2;\n"
                           "\tradius1 = x + left;\n"
                           "\tcall main;\n"
                           "}";

    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");
    REQUIRE_THROWS_AS(CallLoopChecker::checkCallLoop(AST), InvalidSyntaxException);
}

TEST_CASE("checkCallLoop - Negative Case - Procedure call loop")
{
    string rawSourceCode = "procedure main {\n"
                           "\tprint = x;\n"
                           "\tread x;\n"
                           "\tleft = x;\n"
                           "\tright = left + 2;\n"
                           "\tread temp;\n"
                           "\tradius = x + left;\n"
                           "\ttemp = temp + 2;\n"
                           "\tradius1 = x + left;\n"
                           "\tcall somethingHmm;\n"
                           "}\n"
                           "\n"
                           "procedure somethingHmm {\n"
                           "\twhile (iter <=  5) {\n"
                           "\t\tx = right + 3 + 2 + left;\n"
                           "\t\ttemp = temp + 7;\n"
                           "\t\tcall main;\n"
                           "\t}\n"
                           "\tx = 5;\n"
                           "\tif (iter != 1) then {\n"
                           "\t\titer = iter + 1; \n"
                           "\t\tlength = radius * 10;\n"
                           "\t\tbreadth = radius + 10;\n"
                           "\t} else {\n"
                           "\t\twhile ((left + 1 > 2) || (radius + 1 > 2)) {\n"
                           "\t\t\tlength = left + right;\n"
                           "\t\t}\n"
                           "\t}\n"
                           "}";

    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");
    REQUIRE_THROWS_AS(CallLoopChecker::checkCallLoop(AST), InvalidSyntaxException);
}

TEST_CASE("checkCallLoop - Negative Case - Calling non-existent procedure")
{
    string rawSourceCode = "procedure main {\n"
                           "\tprint = x;\n"
                           "\tread x;\n"
                           "\tleft = x;\n"
                           "\tright = left + 2;\n"
                           "\tread temp;\n"
                           "\tradius = x + left;\n"
                           "\ttemp = temp + 2;\n"
                           "\tradius1 = x + left;\n"
                           "\tcall somethingHmm;\n"
                           "}";

    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");
    REQUIRE_THROWS_AS(CallLoopChecker::checkCallLoop(AST), InvalidSyntaxException);
}

TEST_CASE("checkCallLoop - Negative Case - Repeated procedure name")
{
    string rawSourceCode = "procedure main {\n"
                           "\tprint = x;\n"
                           "\tread x;\n"
                           "\tleft = x;\n"
                           "\tright = left + 2;\n"
                           "\tread temp;\n"
                           "\tradius = x + left;\n"
                           "\ttemp = temp + 2;\n"
                           "\tradius1 = x + left;\n"
                           "}\n"
                           "\n"
                           "procedure main {\n"
                           "\tprint x;\n"
                           "}";

    shared_ptr<SourceCode> AST = Parser::parseSourceCode(rawSourceCode, "filename");
    REQUIRE_THROWS_AS(CallLoopChecker::checkCallLoop(AST), InvalidSyntaxException);
}
