#pragma once

#ifndef TEAM37_RELATIONALOPERATOR_H
#define TEAM37_RELATIONALOPERATOR_H

enum RelationalOperator {
    LESS_THAN,
    LESS_THAN_OR_EQUALS,
    GREATER_THAN,
    GREATER_THAN_OR_EQUALS,
    EQUALS,
    NOT_EQUALS
};

#endif
